---
- hosts: ppm
  gather_facts: false
  tasks:
  - name: restart uim probe
    command: /etc/init.d/nimbus restart
#    service:
#      name: nimbus
#      state: restarted
  tags:
    - restart

- hosts: ppm
  gather_facts: false
  tasks:
  - name: start uim probe
    command: /etc/init.d/nimbus start
#    service:
#      name: nimbus
#      state: started
  tags:
    - start

- hosts: ppm
  gather_facts: false
  tasks:
  - name: stop uim probe
    command: /etc/init.d/nimbus stop
#    service:
#      name: nimbus
#      state: stopped
#    register: result
#  - debug: var=result.stdout_lines
  tags:
    - stop

...