---
# os_config_timezone - Configure the timezone on the local machine (because PPM does not support this yet).
- hosts: all,!build
#  remote_user: root
#  become: true
  roles:
    - os-config-timezone
...