---
- hosts: sc5,mun,au1
  gather_facts: false
  roles:
    - os_config_etc_passwd
  tags:
    - os_config_etc_passwd

- hosts: sc5,mun,au1
  gather_facts: false
  roles:
    - os_config_etc_group
  tags:
    - os_config_etc_group

- hosts: us5
  gather_facts: false
  roles:
    - os_config_ssh_key
  tags:
    - os_config_ssh_key
...