---
  - name: Check /etc/passwd for clarity1
    lineinfile:
      path: /etc/passwd
      #dest: /etc/passwd  #Ansible <2.2
      regexp: '^clarity1'
      line: '{{ os_config_etcpasswd_line }}'
      backup: yes
    register: result

  - name: Get value from misconfigured servers
    shell: "grep '^clarity1' /etc/passwd"
    register: value
    check_mode: no
    #always_run: yes #Ansible <2.2
    ignore_errors: true
    changed_when: true == false

  - debug: var=value.stdout_lines
    when: result|changed
    changed_when: true == false

  - name: Check /etc/group
    lineinfile:
      path: /etc/group
      #dest: /etc/group  #Ansible <2.2
      regexp: '{{ os_config_etcgroup_regex }}'
      line: '{{ os_config_etcgroup_line }}'
      backup: yes
    register: result
#   #check_mode: yes

  - name: Get value from misconfigured servers
    shell: "grep {{ os_config_etcgroup_line }} /etc/group"
    register: value
    check_mode: no
#    always_run: yes #Ansible <2.2
    ignore_errors: true
    when: result|changed
    changed_when: true == false

  - debug: var=value.stdout_lines
    when: result|changed
    changed_when: true == false
...