---
- name: Install commonly used packages
  yum: name={{ item }} state=latest
  with_items:
    - bind-utils
    - dialog
    - expect
#    - htop # In a non-default repo
#    - iftop # In a non-default repo
    - net-snmp-utils
#    - python2-simplejson # In a non-default repo
#    - telnet # Great for troubleshooting but CIS audits get angry
    - unzip
    - vim
    - wget
  register: result_yum
# TERRAFORM https://releases.hashicorp.com/terraform/0.10.7/terraform_0.10.7_linux_amd64.zip
