---
- name: Install commonly used packages
  yum: name={{ item }} state=latest
  with_items:
    - bind-utils
    - dialog
    - expect
    - htop
    - iftop
    - net-snmp-utils
    - python2-simplejson
#    - telnet
    - vim
    - wget
  register: result_yum
# TERRAFORM https://releases.hashicorp.com/terraform/0.10.7/terraform_0.10.7_linux_amd64.zip
